import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-base-100`}>
        {/* Navbar DaisyUI */}
        <nav className="navbar bg-base-200 mb-8">
          <div className="container mx-auto flex justify-between items-center">
            <Link className="btn btn-ghost text-xl" href="/">Portofolio</Link>
            <ul className="menu menu-horizontal px-1">
              <li><a href="/about">About</a></li>
              <li><a href="/projects">Projects</a></li>
              <li><a href="/skills">Skills</a></li>
              <li><a href="/contact">Contact</a></li>
            </ul>
          </div>
        </nav>
        <main className="min-h-[70vh] container mx-auto">{children}</main>
        {/* Footer DaisyUI */}
        <footer className="footer footer-center p-4 bg-base-200 text-base-content mt-8">
          <aside>
            <p>© {new Date().getFullYear()} DenisXDaus. All rights reserved.</p>
          </aside>
        </footer>
      </body>
    </html>
  );
}
